### ISSUE TITLE
【台達電子徵才】Java 資深軟體工程師_台北內湖

### ISSUE THREAD

**Issue by MandyYao** [twjug/jobs#2]
## 團隊簡介
台達知識管理部, 負責台達集團知識蒐集、分析、與活用的工作。

在知識經濟的時代，許多商業上的成功，都和善用企業無形資產有關，而企業中最重要的無形資產之一便是人才，尤其是長久待在企業的老員工，他們身經百戰，擁有豐富的經驗，如果這些知識經驗能夠傳承，不因為員工的離開而丟失，那麼便可奠定企業長久獲利、永續經營的基石。透過我們搭建的企業的知識平台，有效蒐集、累積、運用這些知識經驗，突破資訊與知識的藩籬，讓複雜的工作，可以輕鬆完成，進而提高 ROI，增加獲利能力。

## 工作內容
1.SA/SD文件撰寫
2.程式開發
3.新技術研究、推廣
## 能力需求
1.具軟體專案五年以上開發經驗(含JAVA EE相關專案三年以上開發經驗)
2.熟悉Spring framework
 3.熟悉物件導向分析與設計要領
4.熟悉MongoDB相關程式開發
5.熟悉多執行緒運算、分散式運算
6.樂觀、積極、樂於團隊合作，並願意主動積極幫助同事與分享經驗
7.具閱讀英文技術文章能力 
### 加分
1.熟悉Design Pattern
 2.熟悉Solr search engine
 3.熟悉SSO機制
4.熟悉Test-driven development
 5.瞭解CI/CD並有相關經驗
6.熟悉MQ機制與程式開發
7.熟悉Linux系統管理
8.熟悉OpenStack
9.參與軟體產品開發經驗 ## 薪資範圍

## 工時/特休
8:30-17:30
週休二日，依國定假日休假
 特休假依勞基法規定
 每年黃金旅遊週
## 薪資範圍
年終獎金固定2個月 + 績效獎金2個月(表現前90%者) + 現金分紅(依營運狀況與個人績效)
## 福利/推薦項
1.新人訓練
2.專業/職能訓練：研發及工程、行銷/銷售、財務/管理、進出口/採購、資訊科技等專業訓練
3.管理才能訓練：基層、中階及高階管理訓練
4.通識教育訓練：公司價值觀、顧客滿意、品質、安全及衛生
5.專案導向訓練：企業議題討論會/研討會
6.自我發展訓練：語言課程、數位學習

## 聯絡方式
mandy.wl.yao@deltaww.com

**Comment by pintse** [comment]
轉貼一些最近的報導：

台達啟動校園徵才，新鮮人百萬年薪不是夢
作者 TechNews | 發布日期 2018 年 03 月 01 日 17:35
https://technews.tw/2018/03/01/delta-recruitment/

招手新鮮人！ 台達電、台泥祭出百萬年薪
５７東森財經新聞台 Published on Mar 2, 2018
https://www.youtube.com/watch?v=nT_wpUptwvk

新鮮人年薪百萬不是夢！台達電今年開1600個職缺
蘋果即時出版時間：2018/03/01 16:39
https://tw.appledaily.com/new/realtime/20180301/1306374/

新鮮人百萬年薪不是夢 台達電釋1,600個職缺
2018-03-01 16:28經濟日報 記者詹惠珠╱即時報導
https://money.udn.com/money/story/5641/3006654

達電啟動智能科技校園招募 百萬年薪不是夢
2018-03-01 18:31經濟日報 記者劉怡妤╱即時報導
https://money.udn.com/money/story/5641/3006947

台達電徵大數據分析人才 年薪可達百萬
【2017-03-03╱記者劉怡妤╱即時報導】
https://udndata.com/ndapp/udntag/finance/Article?origid=2318644

**Comment by pintse** [comment]
持續徵才中，
歡迎認同Clean Code的開發者應徵！

**Comment by pintse** [comment]
台達啟動校園徵才，新鮮人百萬年薪不是夢
作者 TechNews | 發布日期 2018 年 03 月 01 日 17:35
https://technews.tw/2018/03/01/delta-recruitment/

招手新鮮人！ 台達電、台泥祭出百萬年薪
５７東森財經新聞台 Published on Mar 2, 2018
https://www.youtube.com/watch?v=nT_wpUptwvk

新鮮人年薪百萬不是夢！台達電今年開1600個職缺
蘋果即時出版時間：2018/03/01 16:39
https://tw.appledaily.com/new/realtime/20180301/1306374/

新鮮人百萬年薪不是夢 台達電釋1,600個職缺
2018-03-01 16:28經濟日報 記者詹惠珠╱即時報導
https://money.udn.com/money/story/5641/3006654

台達電啟動智能科技校園招募 百萬年薪不是夢
2018-03-01 18:31經濟日報 記者劉怡妤╱即時報導
https://money.udn.com/money/story/5641/3006947

台達電徵大數據分析人才 年薪可達百萬
【2017-03-03╱記者劉怡妤╱即時報導】
https://udndata.com/ndapp/udntag/finance/Article?origid=2318644

**Comment by pintse** [comment]
因為業務持續成長，
本職缺仍持續擴增招募人材，
歡迎具有上進心好學的Junior Java開發者，
與資深Java好手投遞履歷面試！
