### ISSUE TITLE
【日本】［LINE］Development Engineer/後端工程師

### ISSUE THREAD

**Issue by kojilin** [twjug/jobs#35]
## 地點
Both Japanese speakers and Non-Japanese speakers welcomed (if working in Fukuoka/ Kyoto); there are many English speakers working with the company. Successful applicants without Japanese language skills may be asked to attend a Japanese training course for half of every working day for at least 3 months ~ 12 months after arriving in Fukuoka/ Kyoto. This training is paid for by the employer, and is an excellent chance to pick up new language skills. We encourage employees to reach JLPT Level 2 within few years of commencement.
Choose your work location depending on your Japanese language skills!

1.  Non-Japanese Speakers: Assigned to Fukuoka/ Kyoto office. However, those wishing to transfer to Tokyo office may do so after attaining basic conversational skills if desired.

1.  Japanese Speakers: Can select Tokyo/ Fukuoka/ Kyoto office if Japanese skills equivalent to JLPT Level 2 or above.
Many of the world's best engineers work with the company, and approximately 30% of them hail from overseas. Experienced IT engineers who can put the user's perspective first and wish to make a positive impact on the tens of millions of daily users are encouraged to apply!

## 工作內容
After inquiring about your experience as an engineer and future career preferences, we will assign you to work on either server-side or application development.

You will be performing API/web application design and development work for server-side features that accompany LINE’s messaging and social graph services or related services (referred to as “LINE Family Apps” below) running on the LINE platform.

Systems include:
- Much of the API, client-server/server-server coordination, databases, and parallel batch jobs.
- Responsibilities include:
- Working to achieve scalability, stability, ease-of-use, and flexibility for continual improvements in the services.
- Working to improve work product quality from an engineering standpoint through code reviews and teamwork.
- Examples of Server Development Work
- Service development for paid content and sponsored content on LINE.
- Service development for LINE Family Apps (e.g. “LINE Creators Market”, “LINE Fortune”, “LINE Surveys”, “LINE Part Time Jobs”, etc.).

Responsibilities include:
- Collaborating with the Planning and Design teams to bring ideas to life (e.g. through coding, creating unit tests, etc.).
- Performing app profiling and improving performance.
- Improving and maintaining a CI environment that supports stable development by a large group.
- Developing new features.
- Improving code quality through code reviews.

Main Technologies Utilized:
Java, Kotlin, Perl, Python, JavaScript, MySQL, Redis, Kafka, Git, Spring, Thrift, Hadoop, HBase, Hive, etc.

## 能力需求

- English language skills (business level or above)
- Professional knowledge of at least one programming language
- Understanding of computer science
- Fundamental knowledge of memory, processes, threads, and their relation to programming
- A fundamental understanding of network technology (e.g. TCP/UDP, HTTP, etc.), databases, and SQL

### 加分
- Experience in Web application development using languages such as Java, PHP, Perl, Ruby, Python, etc.
- A history of active participation in the Open Source community
- Experience with development/operation of systems with large quantities of data and traffic

## 薪資範圍
Minimum 6 million Japanese Yen per annual (higher compensation will be provided based on skills and experience and is negotiable). We also offer relocation allowance to the right candidate

## 工時/特休
Discretionary and flexible according to abilities and speed of task completion; if all tasks and projects are completed well and on time, you do not need to stay in the office for extended periods of time.

## 聯絡方式
Send your CV to lfk_dev_recruit@linecorp.com

**Comment by kojilin** [comment]
還很缺喔～

**Comment by haocheng** [comment]
幫推 👍
