### ISSUE TITLE
[台北內湖] [XTEAM STUDIO] JAVA Backend Developer

### ISSUE THREAD

**Issue by Aprilyeh** [twjug/jobs#46]
## 團隊簡介
XTEAM Studio是一支經驗豐富、擁抱熱情、成員組成年齡平均30歲的年輕活力團隊。我們擁抱改變、充滿活力、渴望尋找更效的解決方案。

我們關心、開放、鼓勵每位員工用自己的方式展現工作，無論是 In-house 或 Remote。喜歡步調快、跨團隊合作的工作模式嗎？ 你在尋求一個友善的環境嗎? 歡迎一起加入我們的行列！

## Responsibitily
-Design and develop logic components and application.
-Work closely with the product owner, other developers and testing engineers to shape the product, proactively gather requirements and ensure high quality of our software.
-Ensure our products are tested, extensible, maintainable, secure and perform well.
-Need to be proficient in troubleshooting and efficiently debugging code.
-Influence how and what we build with demonstrated technical expertise.
-Proactively reviews and tests own work; provide peer-review of work of others.
-Willing to work with the team and other developers across the studio to continuously improve our approach to development.
-Ensures clear documentation of created/modified functionality.
-Capable of independently proposing and creating solutions when being given a specific level of control.
-Pursue the better code quality and performance.

## Requirement
-BS in Computer Science or STEM Majors 
-Years of effective experience in enterprise-level Java development, seniority will be evaluated during interview process. 
-Experience in building scalable and robust module and APIs. 
-Experience with SOA or microservices architecture design. 
-Passionate about new technologies, self-learning, good teamwork and communication skills. 
-Experience with SQL and NoSQL Database. 
-Good understanding of cloud-native applications and infrastructure, especially GCP/AWS.

### Nice to Have: 
-BS in Computer Science or STEM Majors. 
-Event driven, parallel programming, non-blocking IO, distributed system. 
-Docker and Kubernetes. 
-Java,Spring, Oracle, Redis, Git, Docker.

## 薪資範圍
600K ~ 2M TWD / 年

## 福利/推薦項
-獎金鼓勵計劃
-彈性工作時間
-免費下午茶
-生日支薪假期
-週三運動日
-旅遊遠端工作
等等，基本款就不另外說了

## XTEAM官網
http://www.xteamstudio.com/

## 聯絡方式
Lisa
請將履歷表寄至lisa.wei@xteamstudio.com

**Comment by Jason00blabla** [comment]
已解散
