### ISSUE TITLE
熱愛新聞和社會議題的工程師看過來！！！！

### ISSUE THREAD

**Issue by juliachiawenliu** [twjug/jobs#57]
＃招才文＃你對台灣的媒體文化很有意見？＃你對社會議題很有想法？ ＃你剛好是工程師？

你是後端工程師嗎？你熱愛新聞媒體、熱愛資料分析嗎？
你會 RDBMS和NoSQL DB，Python、Golang、Java 或 Scala嗎？

**職缺**：後端工程師

**公司名稱**：鏡傳媒-READr

**職缺能力經歷要求**：
- 熟悉 python，golang，Java 或 Scala 其中一種程式語言
- 熟悉 RDBMS 及 NoSQL DB 的使用
- 會使用 git 進行版本控制
- 曾經實作 restful web services
- 對資料分析有興趣者佳
- 熟 Docker，Kubernates 尤佳

**人格特質**：
- 對學習新技術有熱情
- 喜歡 Open Source 文化者

薪資：4-8 萬/月（年薪 13 個月）

**優點**：
1. 公平自由的決策方式有新的功能/想法時每個人都可以貢獻，團隊會根據數據 、A/B test 、使用者訪談的決策方式來決定否採納
2.自由新創的工作環境

**缺點**：
1. 辦公室陽春，秉持車庫創業的精神（誤
2. 距離捷運比較遠（南京三民約走路 5 分鐘，市政府站約 10 分鐘
3. 只有提供員工外接螢幕，沒有外接鍵盤跟滑鼠
4. 程式碼都在 github 上，code 寫不好會被發現

為了幫助大家決定要不要投這份履歷時，我幫大家搜集一些內部同仁和公司的資料，大家也可以幫忙補充💪

**公司簡介**：READr是一個新聞產製實驗室， 『READr』是代表Reporter、Engineer、Audience、Designer的縮寫，這也是團隊的成員主要的工作內容。讓開放新聞編輯室不再只是口號！不由單方主導，讓新聞有不同的面貌。過去的報導主題有：『>政治獻金』『選舉專題』『玩命運輸』『空汙專題』等。
官網：https://www.readr.tw/
裡面的頭頭：https://medium.com/@hsinchanchien

心動了嗎？請投履歷至hcchien@mirrormedia.mg

**Comment by mccken** [comment]
可以问下你们的技术栈吗？

**Comment by juliachiawenliu** [comment]
可以寫信問hcchien@mirrormedia.mg
